# Site settings
name: Yellow Feather Ltd
title: Yellow Feather Ltd
email: chris@yellowfeather.com
description: > # this means to ignore newlines until "baseurl:"
  I help aerospace MRO's and parts suppliers improve their operational efficiency with modern ERP and reporting software built on top of legacy systems
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yellowfeather.co.uk" # the base hostname & protocol for your site
author: yellowfeatheruk

logo: /img/logo.png

exclude: ['README.md', 'CNAME', 'Gemfile.lock', 'Gemfile']

twitter:
  username: yellowfeatheruk

github:
  username:  yellowfeather

# Disqus Comments
disqus_short_name: yellowfeather
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-85823-1

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Outputting
permalink: /blog/:title/

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: assets/sass
  style: :compressed

feed:
  path: atom.xml

# Pagination
paginate: 4
paginate_path: "/blog/page:num/"
