---
title: Yellow Feather Ltd
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Yellow Feather Ltd
email: chris@yellowfeather.com
description: 'I help aerospace MRO''s and parts suppliers improve their operational
  efficiency with modern ERP and reporting software built on top of legacy systems

'
baseurl: ''
url: https://yellowfeather.com
author: yellowfeatheruk
logo: "/img/logo.png"
exclude:
- README.md
- CNAME
- Gemfile.lock
- Gemfile
twitter:
  username: yellowfeatheruk
github:
  username: yellowfeather
disqus_short_name: yellowfeather
disqus_show_comment_count: false
google_analytics_tracking_id: UA-85823-1
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: "/blog/:title/"
gems:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
- jekyll-seo-tag
sass:
  sass_dir: assets/sass
  style: :compressed
feed:
  path: atom.xml
paginate: 4
paginate_path: "/blog/page:num/"
